// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDS7WNGsuKGYzE0m8CtXpJO1KZ8iZUZk',
    appId: '1:529705678722:web:aae1697d2c1f54f5e0019b',
    messagingSenderId: '529705678722',
    projectId: 'reviseapp-c8fbd',
    authDomain: 'reviseapp-c8fbd.firebaseapp.com',
    storageBucket: 'reviseapp-c8fbd.appspot.com',
    measurementId: 'G-05WXWQN00K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2v5ndTDVYdSz2xYjy4LQ6Kl4NrPoEcU',
    appId: '1:529705678722:android:87cd3f71b4e948f5e0019b',
    messagingSenderId: '529705678722',
    projectId: 'reviseapp-c8fbd',
    storageBucket: 'reviseapp-c8fbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmP_wlYoSyIYF0QGAPQK8Xb5ZlypmxxWI',
    appId: '1:529705678722:ios:b833de447200b071e0019b',
    messagingSenderId: '529705678722',
    projectId: 'reviseapp-c8fbd',
    storageBucket: 'reviseapp-c8fbd.appspot.com',
    androidClientId: '529705678722-fttg0ci9ql9eb5hbqkudcnhqag3nvnqr.apps.googleusercontent.com',
    iosClientId: '529705678722-174uc88t2ndhd74khdevqbruau579gaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.revi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmP_wlYoSyIYF0QGAPQK8Xb5ZlypmxxWI',
    appId: '1:529705678722:ios:b833de447200b071e0019b',
    messagingSenderId: '529705678722',
    projectId: 'reviseapp-c8fbd',
    storageBucket: 'reviseapp-c8fbd.appspot.com',
    androidClientId: '529705678722-fttg0ci9ql9eb5hbqkudcnhqag3nvnqr.apps.googleusercontent.com',
    iosClientId: '529705678722-174uc88t2ndhd74khdevqbruau579gaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.revi',
  );
}
